### ISSUE TITLE
light/grey color

### ISSUE THREAD

**Issue by elig0n** [jaredgorski/fogbell.vim#3]
I could not get the lighter/grey background version with neither gvim nor terminal. 
Is it merely a terminal colorscheme then in the screenshot ?

**Comment by jaredgorski** [comment]
Hi!

If you install all three files in `colors` (this happens automatically if you use a plugin manager, or you can put all three files in `~/.vim/colors`), you can then declare whichever colorscheme you want to use in your `~/.vimrc`. To use `fogbell_lite`, you can declare:

```vim
colorscheme fogbell_lite
```

Does that help?
